const TIPO_DATO = {
    DECIMAL: 'VAL_DECIMAL',
    CADENA: 'VAL_CADENA',
    BANDERA: 'VAL_BOOLEAN',
    ENTERO: 'VAL_ENTERO',
    CARACTER: 'VAL_CARACTER',
    VECTOR: 'VAL_VECTOR',
    LISTA: 'VAL_LISTA'
}

module.exports = TIPO_DATO