const TIPO_INSTRUCCION = {
    PRINT: 'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'INST_ASIGNACION',
    EJECUTAR : 'INST_EJECUTAR',//PARA EXEC
    DECLARACION_M: "INST_DECLARACION_METODO",
    DECLARACION_F: "INST_DECLARACION_FUNCION"

}

module.exports = TIPO_INSTRUCCION