const TIPO_OPERACION = {
    SUMA: 'SUMA',
    RESTA: 'RESTA',
    MULTIPLICACION: 'MULTIPLICACION',
    DIVISION: 'DIVISION',
    POTENCIA: 'POTENCIA',
    MODULO: 'MODULO',
    NEGACION: 'NEGACION',
    //---------------------------------------------
    IGUALIGUAL: 'IGUALIGUAL',
    DIFERENTE: 'DIFERENTE',
    MENOR: 'MENOR',
    MENORIGUAL: 'MENORIGUAL',
    MAYOR: 'MAYOR',
    MAYORIGUAL: 'MAYORIGUAL',
    OR: 'OR',
    AND: 'AND',
    NOT: 'NOT',
    TERNARIO: "TERNARIO",
    LENGTH:"LENGTH",
    LOWER:"TO_LOWER",
    UPPER:"TO_UPPER",
    TRUNCATE:"TRUNCATE",
    ROUND:"ROUND",
    TYPEOF: "TYPEOF",
    TOCHARARRAY:"TO_CHAR_ARRAY"
}
module.exports= TIPO_OPERACION;